### ISSUE TITLE
Marketify Road Map / Future Plans

### ISSUE THREAD

**Issue by adampickering** [Astoundify/marketify#134]
- [x]  Checkout / purchase your wishlist items, when accessing your wishlists you should be able to add all products to cart and checkout
- [x] Ability to add more than one wish-list and be able to edit the name of each wishlist
- [ ] Ability to purchase single product in a bundle, i.e.. someone is offering a photo pack, but the user only wants to purchase one file in the bundle.
- [x] Ability to add sub categories on the shop grid page.
